### ISSUE TITLE
In collection page, when we click on the quick view, at that time in live we have add to wishlist button with sold out product but in preview we don't have the add to wishlist button.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Ilovecharacters-Recurring#1]
**Actual result:**
In collection page, when we click on the quick view, at that time in live we have add to wishlist button with sold out product but in preview we don't have the add to wishlist button.
![image](https://user-images.githubusercontent.com/102131636/166206762-d5a2c04b-9934-4b10-9322-32d4c8a2979d.png)

**Expected result:**
The add to wishlist button have to be added in preview , the below image is of live site attached below.
![image](https://user-images.githubusercontent.com/102131636/166206875-101b0e12-0174-40af-a734-ca20cf2893dc.png)

**Comment by devRitikTamrakar** [comment]
Fixed

**Comment by sudhanshu0603** [comment]
ok, resolved
